export type Persona = 'personal' | 'business';

export interface StepItem {
  title: string;
  description: string;
}

export interface PersonaContent {
  heroTitle: [string, string];
  heroSub: string;
  videoLabel: string;
  youtubeId: string;
  stepsTitle: string;
  stepsSub: string;
  steps: StepItem[];
}

export const PERSONAS: Record<Persona, PersonaContent> = {
  personal: {
    heroTitle: ['Your universal', 'crypto wallet'],
    heroSub:
      'Pay for anything with any token — UniCard handles cross-chain routing automatically. One balance, any chain.',
    videoLabel: 'UXmaxx Hackathon · 2026',
    youtubeId: 'yiQNPOPUZo8',
    stepsTitle: 'The easiest way to pay with crypto',
    stepsSub:
      'Sign in with a passwordless method, pay with assets on any supported chain, and access your purchase in seconds.',
    steps: [
      {
        title: 'Passwordless Sign-In',
        description:
          'Login with your email or social accounts. No seed phrases, browser extensions, or passwords required.',
      },
      {
        title: 'Unified Cross-Chain Balance',
        description:
          'Your wallet upgrades seamlessly via EIP-7702. We aggregate your balances across all networks into a single balance, without migrating your address.',
      },
      {
        title: 'Pay with Any Asset',
        description:
          'Use the crypto you already hold. We handle cross-chain routing, token swaps, and gas abstraction automatically in the background.',
      },
      {
        title: 'Instant On-chain Access',
        description:
          'Your payment executes in seconds, and a verifiable on-chain receipt (Pass) is automatically minted directly to your wallet.',
      },
    ],
  },
  business: {
    heroTitle: ['Accept any token.', 'Settle on Arbitrum.'],
    heroSub:
      'The chain-abstracted checkout engine — customers pay with any asset on any chain, you receive USDC on Arbitrum.',
    videoLabel: 'UXmaxx Hackathon · 2026',
    youtubeId: 'yiQNPOPUZo8',
    stepsTitle: 'The Stripe checkout of Web3',
    stepsSub:
      'Integrate UniCard in minutes. Let customers pay with any asset on any chain, while you receive USDC on Arbitrum with instant on-chain receipts.',
    steps: [
      {
        title: 'API Integration',
        description:
          'Create a checkout session with one simple POST request—just like Stripe. No smart contracts to write, audit, or deploy.',
      },
      {
        title: 'Frictionless Buyer Experience',
        description:
          'Redirect users to a secure UniCard checkout page. We handle the passwordless login and smart-account upgrades instantly.',
      },
      {
        title: 'Cross-Chain Payment Routing',
        description:
          'Buyers pay efficiently with any asset across any supported chain. Particle Universal Accounts route all funds automatically.',
      },
      {
        title: 'Instant Webhooks & Settlement',
        description:
          'Our backend fires an instant webhook on success. Payments settle securely as USDC in the platform treasury on Arbitrum, while the buyer receives a verifiable on-chain Pass.',
      },
    ],
  },
};

export interface FaqItem {
  question: string;
  answer: string;
}

export const FAQ_ITEMS: FaqItem[] = [
  {
    question: 'Is UniCard only for event tickets?',
    answer:
      'No. UniCard is a generic checkout engine. Event ticketing is the demo use case. The same contract can issue passes for memberships, digital goods, gaming items, or any access-gated product.',
  },
  {
    question: 'What is EIP-7702 and why does it matter?',
    answer:
      'EIP-7702 lets your regular wallet (EOA) act as a smart account through a delegation transaction. UniCard uses it so you can pay from a single balance across chains, with each payment routed through the best token and network without changing the wallet address. Users keep their original address forever.',
  },
  {
    question: 'Which chains and tokens are supported?',
    answer:
      'You can pay from any chain supported by Particle Universal Accounts — including Ethereum Mainnet, Arbitrum, Base, Polygon, and Solana — using major assets like USDC, USDT, ETH, and SOL. Whatever you pay with, settlement always arrives as USDC on Arbitrum One.',
  },
  {
    question: 'How is my wallet secured without a seed phrase?',
    answer:
      "There are no private keys or seed phrases to manage! Your wallet is securely generated by Magic Auth and tied directly to your email or social login. Neither UniCard nor the seller has access to your account—you are the only one who can authorize payments, and the EIP-7702 upgrade doesn't change that.",
  },
  {
    question: 'How does cross-chain routing work?',
    answer:
      "When you pay, your Universal Account looks at your balances across all chains, picks the cheapest token and route, and executes the swaps and transfers automatically. There are no bridges to click through and nothing to configure — one tap on your side, one settlement on the seller's.",
  },
  {
    question: 'What does settling in USDC on Arbitrum mean for merchants?',
    answer:
      'Your funds always settle as a single asset on a single chain — USDC on Arbitrum One — no matter what your buyer paid with. That means no exposure to volatile tokens, one treasury to manage, and every settlement comes with a webhook and an Arbiscan-verifiable on-chain receipt.',
  },
  {
    question: 'Why not ERC-1155?',
    answer:
      'For the hackathon, a lightweight custom registry saves gas and development time. Production upgrade path is a standard ERC-1155 drop-in replacement — same contract interface, just adds NFT metadata and wallet display support.',
  },
];
